apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    zone: prod
    version: v1
spec:
  containers:
  - name: hello-ctr
    image: ingjavierr/gateway-course:1.0
    ports:
    - containerPort: 8000