apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-rc
spec:
  replicas: 1
  selector:
    app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-pod
        image: ingjavierr/gateway-course:1.0
        ports:
        - containerPort: 8000